%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Benjamin\OneDrive\Documents\GitHub\EMF_HW4\DATA_HW4.xlsx
%    Worksheet: Feuil1
%
% Auto-generated by MATLAB on 28-Apr-2020 18:26:38

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 4);

% Specify sheet and range
opts.Sheet = "Feuil1";
opts.DataRange = "A3:D941";

% Specify column names and types
opts.VariableNames = ["Name", "SP500COMPOSITETOTRETURNIND", "JPMUNITEDSTATESGOVTBONDUSTOTRETURNIND", "USFEDFUNDSEFFRATEDMIDDLERATE"];
opts.VariableTypes = ["datetime", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "Name", "InputFormat", "");

% Import the data
DATAHW4 = readtable("C:\Users\Benjamin\OneDrive\Documents\GitHub\EMF_HW4\DATA_HW4.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts